### PR TITLE
Added Quest mods created by MinionSquisher

### PR DESCRIPTION
**Pull request by DJLegends1011**
Notice that Nexus site has barely got any update for LOOT so decided to add some to the master lists:
added 2 quests from the Creator MinionSquisher 
- [Regrets](https://www.nexusmods.com/starfield/mods/12506)
- [Lazarus Awakened](https://www.nexusmods.com/starfield/mods/12505)

### CODE REVIEW

**Comment by pStyl3** [comment]
Thanks, but we usually don't add metadata to the masterlists that consists solely out of location data in the form of a `url`.

If we want to add one or more nodes from the following list
```
group
after
req
inc
tag
msg
dirty
clean
```

for a plugin then we have meaningful metadata to add & then we also require a `url`.

Is there anything else you would add for the plugins in this PR?

**Comment by DJLegends1011** [comment]
theres nothing else also how would the proper way to PR nexus mods?

**Comment by DJLegends1011** [comment]
want to help out PRing Verified creations as well

**Comment by pStyl3** [comment]
We can add new plugin entries to the masterlists, if we want to add meaningful information regarding them. Looking at the list above, that means that one or more of such elements need to be given, so:
- a group assignment
- information that the plugin in question needs to load after some other plugin
- that the plugin in question requires another plugin
- that the plugin in question in incompatible to another plugin
- Bash Tag assignments
- some kind of message
- information that a plugin is dirty
- .. or clean

If one or more of these information is given, then a new plugin entry can be made. Though as said, we then also require a link to the mod the plugin is originating from.

All of this is how we manage the masterlists generally speaking and it applies to all kind of plugins, independent of the place where they have been uploaded. So Nexus Mods, AFKMods, Creations and other places are also okay, we don't operate exclusively towards one site.

If you haven't already, I would suggest that you take a look at our documentation:
- [Masterlist Editing](https://loot.github.io/docs/contributing/Masterlist-Editing.html)
- [Regex](https://loot.github.io/docs/contributing/Regular-Expression-Regex.html)

Those pages are a good start to understand our process of creating and editing the masterlists.

**Comment by DJLegends1011** [comment]
I will

**Comment by pStyl3** [comment]
Alright, then I'll close this PR without merging, as it's only intention was to add links to 2 plugins.

**Pull request closed without merging**
